// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as IdbCodecTypes } from "@prisma-next-idb/target-idb/pack";

import type { IdbContractWithTypeMaps, IdbTypeMaps } from "@prisma-next-idb/target-idb/pack";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma-next/contract/types";

export type StorageHash = StorageHashBase<"sha256:aed3ca821d99fc4545d38cf8c180976754852ceae54392e65bacd3849c9a599c">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash = ProfileHashBase<"sha256:9c3dc53697717de6a430cccc6a5b4738f956c513b7997012addca5048dfaa743">;

export type CodecTypes = IdbCodecTypes;
export type LaneCodecTypes = CodecTypes;

export type FieldOutputTypes = {
  readonly Post: {
    readonly id: CodecTypes["idb/string@1"]["output"];
    readonly authorId: CodecTypes["idb/string@1"]["output"];
  };
  readonly User: {
    readonly id: CodecTypes["idb/string@1"]["output"];
    readonly email: CodecTypes["idb/string@1"]["output"];
  };
};
export type FieldInputTypes = {
  readonly Post: {
    readonly id: CodecTypes["idb/string@1"]["input"];
    readonly authorId: CodecTypes["idb/string@1"]["input"];
  };
  readonly User: {
    readonly id: CodecTypes["idb/string@1"]["input"];
    readonly email: CodecTypes["idb/string@1"]["input"];
  };
};
export type TypeMaps = IdbTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = ContractType<
  {
    readonly stores: {
      readonly posts: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byAuthorId: { readonly keyPath: "authorId"; readonly unique: false };
        };
      };
      readonly users: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byEmail: { readonly keyPath: "email"; readonly unique: true };
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly Post: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
      };
      readonly relations: {
        readonly author: {
          readonly to: "User";
          readonly cardinality: "N:1";
          readonly on: {
            readonly localFields: readonly ["authorId"];
            readonly targetFields: readonly ["id"];
          };
        };
      };
      readonly storage: { readonly storeName: "posts"; readonly keyPath: "id" };
    };
    readonly User: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly storeName: "users"; readonly keyPath: "id" };
    };
  }
> & {
  readonly target: "idb";
  readonly targetFamily: "idb";
  readonly roots: { readonly users: "User"; readonly posts: "Post" };
  readonly capabilities: {
    readonly idb: {
      readonly compoundKeys: false;
      readonly ddlOnlyInUpgrade: true;
      readonly returning: false;
      readonly transactionalDDL: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = IdbContractWithTypeMaps<ContractBase, TypeMaps>;

export type Stores = Contract["storage"]["stores"];
export type Models = Contract["models"];
