import CodeBlockWriter from "code-block-writer";
import type { Snapshot, SnapshotModel, SnapshotEnum } from "../../helpers/migrations";
import { prismaToStandaloneTsMap } from "../../helpers/utils";

/**
 * Generate the content of a dmmf.ts file for a migration snapshot.
 * Exports a per-version MigrationSchema interface
 * that provides type-safe access to stores/indexes in migration functions.
 */
export function createDmmfSnapshotFile(
  writer: CodeBlockWriter,
  snapshot: Snapshot,
  options?: {
    outboxSync?: boolean;
    outboxModelName?: string;
    versionMetaModelName?: string;
    includeMetaStore?: boolean;
  }
) {
  const {
    outboxSync = false,
    outboxModelName = "OutboxEvent",
    versionMetaModelName = "VersionMeta",
    includeMetaStore = false,
  } = options ?? {};

  writer.writeLine(`// Auto-generated by idb-client-generator — DO NOT EDIT`);
  writer.blankLine();
  writer.writeLine(`import type { DBSchema } from "idb";`);
  writer.blankLine();

  // Generate per-version MigrationSchema interface
  writeMigrationSchemaInterface(writer, snapshot, {
    outboxSync,
    outboxModelName,
    versionMetaModelName,
    includeMetaStore,
  });
}

function prismaTypeToTs(
  type: string,
  kind: string,
  isList: boolean,
  isRequired: boolean,
  enumMap: Map<string, SnapshotEnum>
): string {
  let tsType: string;
  if (kind === "enum") {
    const enumDef = enumMap.get(type);
    tsType = enumDef ? enumDef.values.map((v) => JSON.stringify(v)).join(" | ") : "string";
  } else {
    tsType = prismaToStandaloneTsMap[type] ?? "unknown";
  }
  if (isList) tsType = `(${tsType})[]`;
  if (!isRequired) tsType = `(${tsType}) | null`;
  return tsType;
}

function writeStoreValueType(writer: CodeBlockWriter, model: SnapshotModel, enumMap: Map<string, SnapshotEnum>) {
  writer.block(() => {
    for (const field of model.fields) {
      const tsType = prismaTypeToTs(field.type, field.kind, field.isList, field.isRequired, enumMap);
      writer.writeLine(`${field.name}: ${tsType};`);
    }
  });
}

function writeMigrationSchemaInterface(
  writer: CodeBlockWriter,
  snapshot: Snapshot,
  options: { outboxSync: boolean; outboxModelName: string; versionMetaModelName: string; includeMetaStore: boolean }
) {
  const { outboxSync, outboxModelName, versionMetaModelName, includeMetaStore } = options;

  const enumMap = new Map(snapshot.enums.map((e) => [e.name, e]));

  writer.writeLine(`export interface MigrationSchema extends DBSchema`).block(() => {
    for (const model of snapshot.models) {
      writer.writeLine(`${model.name}: `).block(() => {
        // Key type
        const keyPath = Array.isArray(model.keyPath) ? model.keyPath : [model.keyPath];
        if (keyPath.length === 1) {
          const field = model.fields.find((f) => f.name === keyPath[0]);
          const tsType = field ? prismaTypeToTs(field.type, field.kind, false, true, enumMap) : "IDBValidKey";
          writer.writeLine(`key: ${tsType};`);
        } else {
          const parts = keyPath.map((k) => {
            const field = model.fields.find((f) => f.name === k);
            const tsType = field ? prismaTypeToTs(field.type, field.kind, false, true, enumMap) : "IDBValidKey";
            return `${k}: ${tsType}`;
          });
          writer.writeLine(`key: [${parts.join(", ")}];`);
        }

        // Value type
        writer.write(`value: `);
        writeStoreValueType(writer, model, enumMap);
        writer.write(`;`).newLine();

        // Indexes
        if (model.indexes.length > 0) {
          writer.writeLine(`indexes: `).block(() => {
            for (const idx of model.indexes) {
              const idxKeyPath = Array.isArray(idx.keyPath) ? idx.keyPath : [idx.keyPath];
              if (idxKeyPath.length === 1) {
                const field = model.fields.find((f) => f.name === idxKeyPath[0]);
                const tsType = field ? prismaTypeToTs(field.type, field.kind, false, true, enumMap) : "IDBValidKey";
                writer.writeLine(`${idx.name}: ${tsType};`);
              } else {
                const parts = idxKeyPath.map((k) => {
                  const field = model.fields.find((f) => f.name === k);
                  const tsType = field ? prismaTypeToTs(field.type, field.kind, false, true, enumMap) : "IDBValidKey";
                  return `${k}: ${tsType}`;
                });
                writer.writeLine(`${idx.name}: [${parts.join(", ")}];`);
              }
            }
          });
        }
      });
    }

    // OutboxEvent + VersionMeta stores
    if (outboxSync) {
      writer.writeLine(`${outboxModelName}: `).block(() => {
        writer.writeLine(`key: [id: string];`);
        writer.write(`value: `).block(() => {
          writer.writeLine(`id: string;`);
          writer.writeLine(`entityType: string;`);
          writer.writeLine(`operation: "create" | "update" | "delete";`);
          writer.writeLine(`payload: unknown;`);
          writer.writeLine(`createdAt: Date;`);
          writer.writeLine(`tries: number;`);
          writer.writeLine(`lastError: string | null;`);
          writer.writeLine(`synced: boolean;`);
          writer.writeLine(`syncedAt: Date | null;`);
          writer.writeLine(`lastAttemptedAt: Date | null;`);
          writer.writeLine(`retryable: boolean;`);
        });
        writer.write(`;`).newLine();
      });
      writer.writeLine(`${versionMetaModelName}: `).block(() => {
        writer.writeLine(`key: [model: string, key: IDBValidKey];`);
        writer.write(`value: `).block(() => {
          writer.writeLine(`model: string;`);
          writer.writeLine(`key: IDBValidKey;`);
          writer.writeLine(`lastAppliedChangeId: string | null;`);
          writer.writeLine(`localChangePending: boolean;`);
        });
        writer.write(`;`).newLine();
      });
    }

    // _idb_meta store
    if (includeMetaStore) {
      writer.writeLine(`_idb_meta: `).block(() => {
        writer.writeLine(`key: string;`);
        writer.writeLine(`value: string;`);
      });
    }
  });
}
