import CodeBlockWriter from "code-block-writer";
import type { Snapshot } from "../../helpers/migrations";

/**
 * Generate the content of a dmmf.ts file for a migration snapshot.
 */
export function createDmmfSnapshotFile(writer: CodeBlockWriter, snapshot: Snapshot) {
  writer.writeLine(`// Auto-generated by idb-client-generator — DO NOT EDIT`);
  writer.blankLine();

  // Export the Snapshot type definition
  writer.write(`export type Snapshot = `).block(() => {
    writer.writeLine(`version: ${snapshot.version};`);
    writer.write(`models: [`).newLine();
    writer.indent(() => {
      for (const model of snapshot.models) {
        writer.block(() => {
          writer.writeLine(`name: ${JSON.stringify(model.name)};`);
          writer.writeLine(`keyPath: ${JSON.stringify(model.keyPath)};`);
          writer.write(`fields: [`).newLine();
          writer.indent(() => {
            for (const field of model.fields) {
              writer.block(() => {
                writer.writeLine(`name: ${JSON.stringify(field.name)};`);
                writer.writeLine(`type: ${JSON.stringify(field.type)};`);
                writer.writeLine(`kind: ${JSON.stringify(field.kind)};`);
                writer.writeLine(`isList: ${field.isList};`);
                writer.writeLine(`isRequired: ${field.isRequired};`);
              });
              writer.write(`,`).newLine();
            }
          });
          writer.writeLine(`];`);
          writer.write(`indexes: [`).newLine();
          writer.indent(() => {
            for (const idx of model.indexes) {
              writer.block(() => {
                writer.writeLine(`name: ${JSON.stringify(idx.name)};`);
                writer.writeLine(`keyPath: ${JSON.stringify(idx.keyPath)};`);
                writer.writeLine(`unique: ${idx.unique};`);
              });
              writer.write(`,`).newLine();
            }
          });
          writer.writeLine(`];`);
        });
        writer.write(`,`).newLine();
      }
    });
    writer.writeLine(`];`);
    writer.write(`enums: [`).newLine();
    writer.indent(() => {
      for (const enumDef of snapshot.enums) {
        writer.block(() => {
          writer.writeLine(`name: ${JSON.stringify(enumDef.name)};`);
          writer.writeLine(`values: ${JSON.stringify(enumDef.values)};`);
        });
        writer.write(`,`).newLine();
      }
    });
    writer.writeLine(`];`);
  });
  writer.blankLine();

  // Export the snapshot value
  writer.write(`export const snapshot: Snapshot = `).block(() => {
    writer.writeLine(`version: ${snapshot.version},`);
    writer.write(`models: [`).newLine();
    writer.indent(() => {
      for (const model of snapshot.models) {
        writer.block(() => {
          writer.writeLine(`name: ${JSON.stringify(model.name)},`);
          writer.writeLine(`keyPath: ${JSON.stringify(model.keyPath)},`);
          writer.write(`fields: [`).newLine();
          writer.indent(() => {
            for (const field of model.fields) {
              writer.block(() => {
                writer.writeLine(`name: ${JSON.stringify(field.name)},`);
                writer.writeLine(`type: ${JSON.stringify(field.type)},`);
                writer.writeLine(`kind: ${JSON.stringify(field.kind)},`);
                writer.writeLine(`isList: ${field.isList},`);
                writer.writeLine(`isRequired: ${field.isRequired},`);
              });
              writer.write(`,`).newLine();
            }
          });
          writer.writeLine(`],`);
          writer.write(`indexes: [`).newLine();
          writer.indent(() => {
            for (const idx of model.indexes) {
              writer.block(() => {
                writer.writeLine(`name: ${JSON.stringify(idx.name)},`);
                writer.writeLine(`keyPath: ${JSON.stringify(idx.keyPath)},`);
                writer.writeLine(`unique: ${idx.unique},`);
              });
              writer.write(`,`).newLine();
            }
          });
          writer.writeLine(`],`);
        });
        writer.write(`,`).newLine();
      }
    });
    writer.writeLine(`],`);
    writer.write(`enums: [`).newLine();
    writer.indent(() => {
      for (const enumDef of snapshot.enums) {
        writer.block(() => {
          writer.writeLine(`name: ${JSON.stringify(enumDef.name)},`);
          writer.writeLine(`values: ${JSON.stringify(enumDef.values)},`);
        });
        writer.write(`,`).newLine();
      }
    });
    writer.writeLine(`],`);
  });
}
