import CodeBlockWriter from "code-block-writer";
import type { MigrationDiff, MigrationOp, AmbiguityNote } from "../../helpers/migrations";

/**
 * Generate the content of a migration.ts file.
 * This is only called when the file does NOT already exist (write-once contract).
 */
export function createMigrationFunctionFile(
  writer: CodeBlockWriter,
  diff: MigrationDiff,
  version: number,
  includeMetaStore: boolean
) {
  writer.writeLine(`// Auto-generated by idb-client-generator`);
  writer.writeLine(`// This file is write-once: it will NOT be overwritten on subsequent generates.`);
  writer.writeLine(`// You may edit this file to customize your migration logic.`);
  writer.blankLine();
  writer.writeLine(`import type { IDBPDatabase, IDBPTransaction, StoreNames } from "idb";`);
  writer.writeLine(`import type { MigrationSchema } from "./dmmf";`);
  writer.blankLine();

  // Write ambiguity comments
  for (const ambiguity of diff.ambiguities) {
    writeAmbiguityComment(writer, ambiguity);
  }

  // Check if this migration has structural IDB ops (store/index changes)
  // Field-level ops are informational only (no IDB DDL), so they don't count
  const hasStructuralOps = diff.ops.some((op) =>
    op.type !== "addField" && op.type !== "removeField" &&
    op.type !== "addEnumValue" && op.type !== "removeEnumValue"
  ) || includeMetaStore;

  if (!hasStructuralOps && diff.ambiguities.length === 0) {
    writeFieldRenameComment(writer);
  }

  writer
    .write(
      `export async function migrate(db: IDBPDatabase<MigrationSchema>, tx: IDBPTransaction<MigrationSchema, StoreNames<MigrationSchema>[], "versionchange">): Promise<void> `
    )
    .block(() => {
      if (includeMetaStore) {
        writer.writeLine(`// [auto] internal metadata store — do not remove`);
        writer.writeLine(`db.createObjectStore("_idb_meta");`);
        writer.blankLine();
      }

      if (diff.ops.length === 0 && !includeMetaStore) {
        writer.writeLine(`// no structural IDB changes`);
        return;
      }

      for (const op of diff.ops) {
        writeOp(writer, op);
      }
    });
}

function writeOp(writer: CodeBlockWriter, op: MigrationOp) {
  switch (op.type) {
    case "createObjectStore":
      writer.writeLine(`// [auto] new model: ${op.name}`);
      writer.writeLine(`db.createObjectStore(${JSON.stringify(op.name)}, { keyPath: ${JSON.stringify(op.keyPath)} });`);
      writer.blankLine();
      break;

    case "deleteObjectStore":
      writer.writeLine(
        `// [auto] dropped model: ${op.name} (DESTRUCTIVE — all ${op.name} records will be deleted)`
      );
      writer.writeLine(`db.deleteObjectStore(${JSON.stringify(op.name)});`);
      writer.blankLine();
      break;

    case "createIndex": {
      const uniqueStr = op.unique ? "unique " : "";
      writer.writeLine(`// [auto] new ${uniqueStr}index on ${op.storeName}.${op.indexName}`);
      writer.writeLine(
        `tx.objectStore(${JSON.stringify(op.storeName)}).createIndex(${JSON.stringify(op.indexName)}, ${JSON.stringify(op.keyPath)}, { unique: ${op.unique} });`
      );
      writer.blankLine();
      break;
    }

    case "deleteIndex":
      writer.writeLine(`// [auto] dropped index: ${op.storeName}.${op.indexName}`);
      writer.writeLine(
        `tx.objectStore(${JSON.stringify(op.storeName)}).deleteIndex(${JSON.stringify(op.indexName)});`
      );
      writer.blankLine();
      break;

    case "addField":
      writer.writeLine(`// [auto] new field: ${op.storeName}.${op.fieldName} (${op.fieldType}${op.isList ? "[]" : ""}${op.isRequired ? ", required" : ", optional"})`);
      if (op.isRequired) {
        writer.writeLine(`// TODO: Existing ${op.storeName} records won't have this field.`);
        writer.writeLine(`// Backfill with a cursor loop if needed:`);
        writer.writeLine(`//   let cursor = await tx.objectStore(${JSON.stringify(op.storeName)}).openCursor();`);
        writer.writeLine(`//   while (cursor) {`);
        writer.writeLine(`//     cursor.update({ ...cursor.value, ${op.fieldName}: <default> });`);
        writer.writeLine(`//     cursor = await cursor.continue();`);
        writer.writeLine(`//   }`);
      }
      writer.blankLine();
      break;

    case "removeField":
      writer.writeLine(`// [auto] removed field: ${op.storeName}.${op.fieldName}`);
      writer.writeLine(`// Existing records may still contain this property.`);
      writer.blankLine();
      break;

    case "addEnumValue":
      writer.writeLine(`// [auto] new enum value: ${op.enumName}.${op.value}`);
      writer.blankLine();
      break;

    case "removeEnumValue":
      writer.writeLine(`// [auto] removed enum value: ${op.enumName}.${op.value}`);
      writer.writeLine(`// TODO: Existing records using "${op.value}" may need to be updated.`);
      writer.writeLine(`// Example cursor migration:`);
      writer.writeLine(`//   let cursor = await tx.objectStore("YourModel").openCursor();`);
      writer.writeLine(`//   while (cursor) {`);
      writer.writeLine(`//     if (cursor.value.field === "${op.value}") {`);
      writer.writeLine(`//       cursor.update({ ...cursor.value, field: "<replacement>" });`);
      writer.writeLine(`//     }`);
      writer.writeLine(`//     cursor = await cursor.continue();`);
      writer.writeLine(`//   }`);
      writer.blankLine();
      break;
  }
}

function writeAmbiguityComment(writer: CodeBlockWriter, ambiguity: AmbiguityNote) {
  if (ambiguity.type === "possibleRename") {
    writer.writeLine(
      `// [auto] Detected: \`${ambiguity.removedModel}\` removed, \`${ambiguity.addedModel}\` added in same migration.`
    );
    writer.writeLine(`// This was generated as DROP + CREATE (data loss for ${ambiguity.removedModel}).`);
    writer.writeLine(`// If this was a rename, replace the body below with a data copy:`);
    writer.writeLine(`//`);
    writer.writeLine(
      `//   const records = await tx.objectStore("${ambiguity.removedModel}").getAll();`
    );
    writer.writeLine(
      `//   db.createObjectStore("${ambiguity.addedModel}", { keyPath: "id" });`
    );
    writer.writeLine(
      `//   for (const r of records) await tx.objectStore("${ambiguity.addedModel}").add(r);`
    );
    writer.writeLine(`//   db.deleteObjectStore("${ambiguity.removedModel}");`);
    writer.blankLine();
  } else if (ambiguity.type === "possibleFieldRename") {
    writer.writeLine(
      `// [auto] Detected: \`${ambiguity.storeName}.${ambiguity.removedField}\` removed, \`${ambiguity.storeName}.${ambiguity.addedField}\` added in same migration.`
    );
    writer.writeLine(`// If this was a field rename, add a cursor migration:`);
    writer.writeLine(`//`);
    writer.writeLine(`//   let cursor = await tx.objectStore(${JSON.stringify(ambiguity.storeName)}).openCursor();`);
    writer.writeLine(`//   while (cursor) {`);
    writer.writeLine(`//     const { ${ambiguity.removedField}: renamed, ...rest } = cursor.value;`);
    writer.writeLine(`//     cursor.update({ ...rest, ${ambiguity.addedField}: renamed });`);
    writer.writeLine(`//     cursor = await cursor.continue();`);
    writer.writeLine(`//   }`);
    writer.blankLine();
  } else if (ambiguity.type === "possibleEnumValueRename") {
    writer.writeLine(
      `// [auto] Detected: \`${ambiguity.enumName}.${ambiguity.removedValue}\` removed, \`${ambiguity.enumName}.${ambiguity.addedValue}\` added in same migration.`
    );
    writer.writeLine(`// If this was a value rename, update existing records:`);
    writer.writeLine(`//`);
    writer.writeLine(`//   let cursor = await tx.objectStore("YourModel").openCursor();`);
    writer.writeLine(`//   while (cursor) {`);
    writer.writeLine(`//     if (cursor.value.field === ${JSON.stringify(ambiguity.removedValue)}) {`);
    writer.writeLine(`//       cursor.update({ ...cursor.value, field: ${JSON.stringify(ambiguity.addedValue)} });`);
    writer.writeLine(`//     }`);
    writer.writeLine(`//     cursor = await cursor.continue();`);
    writer.writeLine(`//   }`);
    writer.blankLine();
  }
}

function writeFieldRenameComment(writer: CodeBlockWriter) {
  writer.writeLine(`// [auto] No IDB-level changes detected for this migration.`);
  writer.writeLine(
    `// NOTE: If you renamed a field (e.g. \`firstName\` → \`givenName\`), existing`
  );
  writer.writeLine(
    `// records still use the old key. Implement a data migration below if needed:`
  );
  writer.writeLine(`//`);
  writer.writeLine(`//   const store = tx.objectStore("YourModel");`);
  writer.writeLine(`//   let cursor = await store.openCursor();`);
  writer.writeLine(`//   while (cursor) {`);
  writer.writeLine(
    `//     cursor.update({ ...cursor.value, newField: cursor.value.oldField });`
  );
  writer.writeLine(`//     cursor = await cursor.continue();`);
  writer.writeLine(`//   }`);
  writer.blankLine();
}
