packages:
  - packages/*
  - apps/*
  - tests

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp

overrides:
  "@hono/node-server@<1.19.10": ">=1.19.10"
  "@types/node": "^24.10.9"
  "cookie@<0.7.0": ">=0.7.0"
  "devalue@<5.6.4": ">=5.6.4"
  effect@<3.20.0: '>=3.20.0'
  "hono@<4.11.10": ">=4.11.10"
  "hono@<4.12.4": ">=4.12.4"
  "hono@<4.12.7": ">=4.12.7"
  kysely@<=0.28.13: '>=0.28.14'
  "lodash@>=4.0.0 <=4.17.22": ">=4.17.23"
  "serialize-javascript@<=7.0.2": ">=7.0.3"
  "undici@<6.24.0": ">=6.24.0"
