import CodeBlockWriter from "code-block-writer";

/**
 * Generate the idb-schema-hash.ts file content.
 * This file is always regenerated on every `prisma generate` run.
 */
export function createSchemaHashFile(writer: CodeBlockWriter, hash: string) {
  writer.writeLine(`// Auto-generated by idb-client-generator — always regenerated`);
  writer.writeLine(`export const IDB_SCHEMA_HASH = ${JSON.stringify(hash)};`);
}
