// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as IdbCodecTypes } from "@prisma-next-idb/target-idb/pack";

import type { IdbContractWithTypeMaps, IdbTypeMaps } from "@prisma-next-idb/target-idb/pack";
import type {
  Contract as ContractType,
  ContractModelsMap,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma-next/contract/types";

export type StorageHash = StorageHashBase<"sha256:b05717321fba711de059ca6e508f0f2087f2eaca7de74beb8f969ac5f0c606d9">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash = ProfileHashBase<"sha256:e97a15c6c5e8cd6446e4f48dc464af667a10a0a4ecb533c9624bbab58233a14d">;

export type CodecTypes = IdbCodecTypes;
export type LaneCodecTypes = CodecTypes;

export type FieldOutputTypes = {
  readonly Post: {
    readonly id: CodecTypes["idb/string@1"]["output"];
    readonly title: CodecTypes["idb/string@1"]["output"];
    readonly content: CodecTypes["idb/string@1"]["output"] | null;
    readonly published: CodecTypes["idb/bool@1"]["output"];
    readonly views: CodecTypes["idb/int32@1"]["output"];
    readonly authorId: CodecTypes["idb/string@1"]["output"];
    readonly createdAt: CodecTypes["idb/date@1"]["output"];
  };
  readonly RandomStore: { readonly id: CodecTypes["idb/string@1"]["output"] };
  readonly User: {
    readonly id: CodecTypes["idb/string@1"]["output"];
    readonly name: CodecTypes["idb/string@1"]["output"];
    readonly email: CodecTypes["idb/string@1"]["output"];
    readonly bio: CodecTypes["idb/string@1"]["output"] | null;
    readonly score: CodecTypes["idb/int32@1"]["output"];
    readonly active: CodecTypes["idb/bool@1"]["output"];
    readonly joinedAt: CodecTypes["idb/date@1"]["output"];
  };
};
export type FieldInputTypes = {
  readonly Post: {
    readonly id: CodecTypes["idb/string@1"]["input"];
    readonly title: CodecTypes["idb/string@1"]["input"];
    readonly content: CodecTypes["idb/string@1"]["input"] | null;
    readonly published: CodecTypes["idb/bool@1"]["input"];
    readonly views: CodecTypes["idb/int32@1"]["input"];
    readonly authorId: CodecTypes["idb/string@1"]["input"];
    readonly createdAt: CodecTypes["idb/date@1"]["input"];
  };
  readonly RandomStore: { readonly id: CodecTypes["idb/string@1"]["input"] };
  readonly User: {
    readonly id: CodecTypes["idb/string@1"]["input"];
    readonly name: CodecTypes["idb/string@1"]["input"];
    readonly email: CodecTypes["idb/string@1"]["input"];
    readonly bio: CodecTypes["idb/string@1"]["input"] | null;
    readonly score: CodecTypes["idb/int32@1"]["input"];
    readonly active: CodecTypes["idb/bool@1"]["input"];
    readonly joinedAt: CodecTypes["idb/date@1"]["input"];
  };
};
export type TypeMaps = IdbTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<
    {
      readonly stores: {
        readonly posts: {
          readonly keyPath: "id";
          readonly indexes: {
            readonly byAuthorId: { readonly keyPath: "authorId"; readonly unique: false };
          };
        };
        readonly random_store: { readonly keyPath: "id"; readonly indexes: Record<string, never> };
        readonly users: {
          readonly keyPath: "id";
          readonly indexes: {
            readonly byEmail: { readonly keyPath: "email"; readonly unique: true };
            readonly byScore: { readonly keyPath: "score"; readonly unique: false };
          };
        };
      };
      readonly namespaces: { readonly __unbound__: { readonly id: "__unbound__" } };
      readonly storageHash: StorageHash;
    },
    {
      readonly Post: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly title: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly content: {
            readonly nullable: true;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly published: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
          };
          readonly views: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
          };
          readonly authorId: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly createdAt: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: { readonly storeName: "posts"; readonly keyPath: "id" };
      };
      readonly RandomStore: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: { readonly storeName: "random_store"; readonly keyPath: "id" };
      };
      readonly User: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly name: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly email: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly bio: {
            readonly nullable: true;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
          };
          readonly score: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
          };
          readonly active: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
          };
          readonly joinedAt: {
            readonly nullable: false;
            readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: { readonly storeName: "users"; readonly keyPath: "id" };
      };
    }
  >,
  "roots" | "domain"
> & {
  readonly target: "idb";
  readonly targetFamily: "idb";
  readonly roots: {
    readonly users: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "User" };
    readonly posts: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Post" };
    readonly random_store: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "RandomStore";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Post: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly content: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly published: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
              readonly views: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
              };
              readonly authorId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly storeName: "posts"; readonly keyPath: "id" };
          };
          readonly RandomStore: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly storeName: "random_store"; readonly keyPath: "id" };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly bio: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly score: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
              readonly joinedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly storeName: "users"; readonly keyPath: "id" };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly idb: {
      readonly compoundKeys: false;
      readonly ddlOnlyInUpgrade: true;
      readonly returning: false;
      readonly transactionalDDL: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = IdbContractWithTypeMaps<ContractBase, TypeMaps>;

export type Stores = Contract["storage"]["stores"];
export type Models = ContractModelsMap<Contract>;
