// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as IdbCodecTypes } from "@prisma-next-idb/target-idb/pack";

import type { IdbContractWithTypeMaps, IdbTypeMaps } from "@prisma-next-idb/target-idb/pack";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma-next/contract/types";

export type StorageHash = StorageHashBase<"sha256:9a439471a6c17853ccf264236b1ef6a4ab268c165938886dd63fab2309eeeff8">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash = ProfileHashBase<"sha256:c115cd9b68c3a59204e40249c979cb44ada95d3a5ccc8a3c7a20ae2008f97b83">;

export type CodecTypes = IdbCodecTypes;
export type LaneCodecTypes = CodecTypes;

export type FieldOutputTypes = {
  readonly Post: {
    readonly id: CodecTypes["idb/string@1"]["output"];
    readonly authorId: CodecTypes["idb/string@1"]["output"];
    readonly title: CodecTypes["idb/string@1"]["output"];
    readonly content: CodecTypes["idb/string@1"]["output"] | null;
    readonly views: CodecTypes["idb/int32@1"]["output"];
    readonly published: CodecTypes["idb/bool@1"]["output"];
    readonly publishedAt: CodecTypes["idb/date@1"]["output"] | null;
  };
  readonly RandomStore: { readonly id: CodecTypes["idb/string@1"]["output"] };
  readonly User: {
    readonly id: CodecTypes["idb/string@1"]["output"];
    readonly name: CodecTypes["idb/string@1"]["output"];
    readonly email: CodecTypes["idb/string@1"]["output"];
    readonly bio: CodecTypes["idb/string@1"]["output"] | null;
    readonly score: CodecTypes["idb/int32@1"]["output"];
    readonly active: CodecTypes["idb/bool@1"]["output"];
    readonly joinedAt: CodecTypes["idb/date@1"]["output"];
  };
};
export type FieldInputTypes = {
  readonly Post: {
    readonly id: CodecTypes["idb/string@1"]["input"];
    readonly authorId: CodecTypes["idb/string@1"]["input"];
    readonly title: CodecTypes["idb/string@1"]["input"];
    readonly content: CodecTypes["idb/string@1"]["input"] | null;
    readonly views: CodecTypes["idb/int32@1"]["input"];
    readonly published: CodecTypes["idb/bool@1"]["input"];
    readonly publishedAt: CodecTypes["idb/date@1"]["input"] | null;
  };
  readonly RandomStore: { readonly id: CodecTypes["idb/string@1"]["input"] };
  readonly User: {
    readonly id: CodecTypes["idb/string@1"]["input"];
    readonly name: CodecTypes["idb/string@1"]["input"];
    readonly email: CodecTypes["idb/string@1"]["input"];
    readonly bio: CodecTypes["idb/string@1"]["input"] | null;
    readonly score: CodecTypes["idb/int32@1"]["input"];
    readonly active: CodecTypes["idb/bool@1"]["input"];
    readonly joinedAt: CodecTypes["idb/date@1"]["input"];
  };
};
export type TypeMaps = IdbTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = ContractType<
  {
    readonly stores: {
      readonly posts: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byAuthorId: { readonly keyPath: "authorId"; readonly unique: false };
        };
      };
      readonly random_store: { readonly keyPath: "id"; readonly indexes: Record<string, never> };
      readonly users: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byEmail: { readonly keyPath: "email"; readonly unique: true };
          readonly byScore: { readonly keyPath: "score"; readonly unique: false };
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly Post: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly content: {
          readonly nullable: true;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly views: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
        };
        readonly published: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
        };
        readonly publishedAt: {
          readonly nullable: true;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
        };
      };
      readonly relations: {
        readonly author: {
          readonly to: "User";
          readonly cardinality: "N:1";
          readonly on: {
            readonly localFields: readonly ["authorId"];
            readonly targetFields: readonly ["id"];
          };
        };
      };
      readonly storage: { readonly storeName: "posts"; readonly keyPath: "id" };
    };
    readonly RandomStore: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly storeName: "random_store"; readonly keyPath: "id" };
    };
    readonly User: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly bio: {
          readonly nullable: true;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
        };
        readonly score: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
        };
        readonly active: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
        };
        readonly joinedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
        };
      };
      readonly relations: {
        readonly posts: {
          readonly to: "Post";
          readonly cardinality: "1:N";
          readonly on: {
            readonly localFields: readonly ["id"];
            readonly targetFields: readonly ["authorId"];
          };
        };
      };
      readonly storage: { readonly storeName: "users"; readonly keyPath: "id" };
    };
  }
> & {
  readonly target: "idb";
  readonly targetFamily: "idb";
  readonly roots: {
    readonly users: "User";
    readonly posts: "Post";
    readonly random_store: "RandomStore";
  };
  readonly capabilities: {
    readonly idb: {
      readonly compoundKeys: false;
      readonly ddlOnlyInUpgrade: true;
      readonly returning: false;
      readonly transactionalDDL: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = IdbContractWithTypeMaps<ContractBase, TypeMaps>;

export type Stores = Contract["storage"]["stores"];
export type Models = Contract["models"];
