// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma-next/adapter-postgres/operation-types";
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma-next/target-postgres/codec-types";

import type { ContractWithTypeMaps, TypeMaps as TypeMapsType } from "@prisma-next/sql-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma-next/contract/types";

export type StorageHash = StorageHashBase<"sha256:401b2b0687bca2ef0fab5ec851a8509b4f58b5b6cb59528e18eefa06c3a4c867">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash = ProfileHashBase<"sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]["output"]
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly action: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
    };
    readonly Board: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly Changelog: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly model: CodecTypes["pg/text@1"]["output"];
      readonly keyPath: CodecTypes["pg/text@1"]["output"];
      readonly operation: "create" | "update" | "delete";
      readonly scopeKey: CodecTypes["pg/text@1"]["output"];
      readonly outboxEventId: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
    };
    readonly Todo: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"] | null;
      readonly isCompleted: CodecTypes["pg/bool@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
      readonly boardId: CodecTypes["pg/text@1"]["output"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"] | null;
      readonly passwordHash: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly action: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
    };
    readonly Board: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly Changelog: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly model: CodecTypes["pg/text@1"]["input"];
      readonly keyPath: CodecTypes["pg/text@1"]["input"];
      readonly operation: "create" | "update" | "delete";
      readonly scopeKey: CodecTypes["pg/text@1"]["input"];
      readonly outboxEventId: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
    };
    readonly Todo: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"] | null;
      readonly isCompleted: CodecTypes["pg/bool@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
      readonly boardId: CodecTypes["pg/text@1"]["input"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"] | null;
      readonly passwordHash: CodecTypes["pg/text@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly auditLog: {
      readonly action: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
    };
    readonly board: {
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly changelog: {
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly keyPath: CodecTypes["pg/text@1"]["output"];
      readonly model: CodecTypes["pg/text@1"]["output"];
      readonly operation: "create" | "update" | "delete";
      readonly outboxEventId: CodecTypes["pg/text@1"]["output"];
      readonly scopeKey: CodecTypes["pg/text@1"]["output"];
    };
    readonly todo: {
      readonly boardId: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"] | null;
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly isCompleted: CodecTypes["pg/bool@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
    };
    readonly user: {
      readonly email: CodecTypes["pg/text@1"]["output"] | null;
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly passwordHash: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly auditLog: {
      readonly action: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
    };
    readonly board: {
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly changelog: {
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly keyPath: CodecTypes["pg/text@1"]["input"];
      readonly model: CodecTypes["pg/text@1"]["input"];
      readonly operation: "create" | "update" | "delete";
      readonly outboxEventId: CodecTypes["pg/text@1"]["input"];
      readonly scopeKey: CodecTypes["pg/text@1"]["input"];
    };
    readonly todo: {
      readonly boardId: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"] | null;
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly isCompleted: CodecTypes["pg/bool@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
    };
    readonly user: {
      readonly email: CodecTypes["pg/text@1"]["input"] | null;
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly passwordHash: CodecTypes["pg/text@1"]["input"];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly auditLog: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly action: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly board: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ["userId"]; readonly name: "board_userId_idx" }];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "board";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly changelog: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly model: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly keyPath: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly operation: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly scopeKey: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly outboxEventId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["outboxEventId"] }];
              indexes: readonly [{ readonly columns: readonly ["scopeKey", "id"] }];
              foreignKeys: readonly [];
            };
            readonly todo: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly isCompleted: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz@1";
                  readonly nullable: false;
                };
                readonly boardId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ["boardId"]; readonly name: "todo_boardId_idx" }];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "todo";
                    readonly columns: readonly ["boardId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "board";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly passwordHash: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["email"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ChangeOperation: {
              readonly kind: "valueSet";
              readonly values: readonly ["create", "update", "delete"];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly user: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
    readonly auditLog: { readonly namespace: "public" & NamespaceId; readonly model: "AuditLog" };
    readonly board: { readonly namespace: "public" & NamespaceId; readonly model: "Board" };
    readonly todo: { readonly namespace: "public" & NamespaceId; readonly model: "Todo" };
    readonly changelog: { readonly namespace: "public" & NamespaceId; readonly model: "Changelog" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AuditLog: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/timestamptz@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "auditLog";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly action: { readonly column: "action" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Board: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/timestamptz@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly todos: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "Todo" };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["boardId"];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "board";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly userId: { readonly column: "userId" };
              };
            };
          };
          readonly Changelog: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly model: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly keyPath: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly operation: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly scopeKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly outboxEventId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/timestamptz@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "changelog";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly model: { readonly column: "model" };
                readonly keyPath: { readonly column: "keyPath" };
                readonly operation: { readonly column: "operation" };
                readonly scopeKey: { readonly column: "scopeKey" };
                readonly outboxEventId: { readonly column: "outboxEventId" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Todo: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly isCompleted: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/timestamptz@1" };
              };
              readonly boardId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly board: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Board";
                };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["boardId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "todo";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly title: { readonly column: "title" };
                readonly description: { readonly column: "description" };
                readonly isCompleted: { readonly column: "isCompleted" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly boardId: { readonly column: "boardId" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly boards: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Board";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: {
              readonly table: "user";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly email: { readonly column: "email" };
                readonly passwordHash: { readonly column: "passwordHash" };
              };
            };
          };
        };
        readonly enum: {
          readonly ChangeOperation: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "create"; readonly value: "create" },
              { readonly name: "update"; readonly value: "update" },
              { readonly name: "delete"; readonly value: "delete" },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
