// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as IdbCodecTypes } from "@prisma-next-idb/target-idb/pack";

import type { IdbContractWithTypeMaps, IdbTypeMaps } from "@prisma-next-idb/target-idb/pack";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma-next/contract/types";

export type StorageHash = StorageHashBase<"sha256:004f476119390a4c2e8ea6d507ac5e9707c7d58d65be963316b827ef42fb756b">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash = ProfileHashBase<"sha256:e97a15c6c5e8cd6446e4f48dc464af667a10a0a4ecb533c9624bbab58233a14d">;

export type CodecTypes = IdbCodecTypes;
export type LaneCodecTypes = CodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly User: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly name: CodecTypes["idb/string@1"]["output"];
      readonly email: CodecTypes["idb/string@1"]["output"] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly User: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly name: CodecTypes["idb/string@1"]["input"];
      readonly email: CodecTypes["idb/string@1"]["input"] | null;
    };
  };
};
export type TypeMaps = IdbTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly stores: {
      readonly user: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly email_unique: { readonly keyPath: "email"; readonly unique: true };
        };
      };
    };
    readonly namespaces: {
      readonly __unbound__: { readonly id: "__unbound__"; readonly entries: Record<string, never> };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "idb";
  readonly targetFamily: "idb";
  readonly roots: {
    readonly user: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "User" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly storeName: "user"; readonly keyPath: "id" };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly idb: {
      readonly compoundKeys: false;
      readonly ddlOnlyInUpgrade: true;
      readonly returning: false;
      readonly transactionalDDL: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = IdbContractWithTypeMaps<ContractBase, TypeMaps>;

export type Stores = Contract["storage"]["stores"];
